# Generated by Django 5.2.6 on 2025-09-30 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=90, verbose_name='발행처 이름 (예: YTN, 조선일보, KBS News)')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='기사/영상 제목')),
                ('url', models.URLField(max_length=300, verbose_name='기사/영상 원본 URL')),
                ('published_date', models.DateTimeField(verbose_name='최초 발행일')),
                ('view_count', models.IntegerField(verbose_name='조회수')),
                ('crawled_at', models.DateTimeField(verbose_name='최종 크롤링 시점')),
                ('publisher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_list', to='news.publisher')),
            ],
        ),
    ]
