# Generated by Django 5.2.6 on 2025-10-07 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='발행처 이름 (예: YTN, 조선일보, KBS News)')),
            ],
        ),
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='기사/영상 제목')),
                ('url', models.URLField(max_length=300, verbose_name='기사/영상 원본 URL')),
                ('published_date', models.DateField(verbose_name='최초 발행일')),
                ('view_count', models.IntegerField(verbose_name='조회수')),
                ('crawled_at', models.DateTimeField(verbose_name='최종 크롤링 시점')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_list', to='news.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='WordCloudResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='집계 시작일')),
                ('end_date', models.DateField(verbose_name='집계 종료일')),
                ('word_frequency_json', models.JSONField(verbose_name='빈도수 JSON 데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='결과 생성 시각')),
                ('image_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='이미지 파일 경로')),
                ('included_publishers', models.ManyToManyField(related_name='wordcloud_results', to='news.publisher', verbose_name='포함된 발행처 목록')),
            ],
            options={
                'verbose_name': '워드클라우드 결과',
                'verbose_name_plural': '워드클라우드 결과 목록',
            },
        ),
    ]
