# Generated by Django 5.2.6 on 2025-10-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='platform',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=180, verbose_name='기사/영상 제목'),
        ),
        migrations.CreateModel(
            name='WordCloudResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='집계 시작일')),
                ('end_date', models.DateField(verbose_name='집계 종료일')),
                ('word_frequency_json', models.JSONField(verbose_name='빈도수 JSON 데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='결과 생성 시각')),
                ('image_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='이미지 파일 경로')),
                ('included_publishers', models.ManyToManyField(related_name='wordcloud_results', to='news.publisher', verbose_name='포함된 발행처 목록')),
            ],
            options={
                'verbose_name': '워드클라우드 결과',
                'verbose_name_plural': '워드클라우드 결과 목록',
            },
        ),
    ]
