# Generated by Django 5.2.6 on 2025-10-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_platform_publisher_name_alter_news_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateField(verbose_name='최초 발행일'),
        ),
    ]
