# Generated by Django 5.2.6 on 2025-10-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_published_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Headline',
        ),
        migrations.RenameField(
            model_name='headline',
            old_name='publisher_id',
            new_name='publisher',
        ),
    ]
