# Generated by Django 5.2.6 on 2025-10-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_news_headline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headline',
            old_name='publisher_id',
            new_name='publisher',
        ),
    ]
